name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - run: go mod tidy
      - uses: ankane/setup-postgres@v1
        with:
          database: pgslice_test
      - run: make test
